version: '3.8'

services:
  backend:
    build: ./JobBoard-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/jobboard?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - jobboard-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jobboard
    networks:
      - jobboard-network

  frontend:
    build:
      context: ./JobBoard-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - jobboard-network

networks:
  jobboard-network:
    driver: bridge
